// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfAVo0rzExEK5epYqG00MJYyS3FZwXKo',
    appId: '1:172344774153:web:740b5dd117911312da32d8',
    messagingSenderId: '172344774153',
    projectId: 'driveguard-c4915',
    authDomain: 'driveguard-c4915.firebaseapp.com',
    databaseURL: 'https://driveguard-c4915-default-rtdb.firebaseio.com',
    storageBucket: 'driveguard-c4915.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPMFXFNxdnHRVocO_NgiMs4wjxfdhTxTo',
    appId: '1:172344774153:android:192b5218819f15c3da32d8',
    messagingSenderId: '172344774153',
    projectId: 'driveguard-c4915',
    databaseURL: 'https://driveguard-c4915-default-rtdb.firebaseio.com',
    storageBucket: 'driveguard-c4915.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRfAVo0rzExEK5epYqG00MJYyS3FZwXKo',
    appId: '1:172344774153:web:13707e6dba0765f5da32d8',
    messagingSenderId: '172344774153',
    projectId: 'driveguard-c4915',
    authDomain: 'driveguard-c4915.firebaseapp.com',
    databaseURL: 'https://driveguard-c4915-default-rtdb.firebaseio.com',
    storageBucket: 'driveguard-c4915.appspot.com',
  );

}